export const ISUSERLOGIN = 'ISUSERLOGIN';
export const ISUSERLOGOUT = 'ISUSERLOGOUT';
export const TEMPORARY_USER_ID = 'TEMPORARY_USER_ID';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_SOCIAL_PROFILE = 'GET_USER_SOCIAL_PROFILE';
export const GET_BEARER_TOKEN = 'GET_BEARER_TOKEN';
